interface Product {
  name: string;
  price: number;
  image: string; // URL or local image path
  username: string;
  avatar: any;
  description: string;
  units: number;
  isSecondHand: boolean;
  negotiable: boolean;
  category: string; // New property
}

export const products: Product[] = [
  {
    name: "Fresh Yogurt",
    price: 50,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/250ml.jpg"),
    description: "Delicious and fresh yogurt, perfect for a healthy snack.",
    units: Math.floor(Math.random() * 50) + 1,
    isSecondHand: false,
    negotiable: false,
    category: "Food & Beverages",
  },
  {
    name: "Strawberry Yogurt",
    price: 100,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/500ml.jpg"),
    description: "Creamy strawberry-flavored yogurt with a rich taste.",
    units: Math.floor(Math.random() * 50) + 1,
    isSecondHand: false,
    negotiable: false,
    category: "Food & Beverages",
  },
  {
    name: "Black Heels",
    price: 1800,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/blackheels.jpg"),
    description: "Elegant black heels for formal and casual occasions.",
    units: Math.floor(Math.random() * 20) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Fashion",
  },
  {
    name: "Sneakers White Shoes",
    price: 3200,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/sneekers.jpg"),
    description: "Trendy white sneakers, comfortable and stylish for daily wear.",
    units: Math.floor(Math.random() * 30) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Fashion",
  },
  {
    name: "2 Seater Sofa",
    price: 25000,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/2 seater sofa.jpg"),
    description: "Comfortable and stylish 2-seater sofa for your living room.",
    units: Math.floor(Math.random() * 10) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Furniture",
  },
  {
    name: "Alyons Woofer",
    price: 4500,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/alyons woofer.jpg"),
    description: "Powerful Alyons woofer with deep bass and clear sound.",
    units: Math.floor(Math.random() * 15) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Electronics",
  },
  {
    name: "Black Two Seater Sofa",
    price: 28000,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/black two seater sofa.jpg"),
    description: "Luxurious black two-seater sofa with a sleek modern design.",
    units: Math.floor(Math.random() * 10) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Furniture",
  },
  {
    name: "Denim Dress",
    price: 3500,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/denim dress.jpg"),
    description: "Stylish denim dress for casual and trendy looks.",
    units: Math.floor(Math.random() * 30) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Fashion",
  },
  {
    name: "Infinix Zero Flip",
    price: 75000,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/infinix zero flip.jpg"),
    description: "Infinix Zero Flip - latest model with high-end features.",
    units: Math.floor(Math.random() * 5) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Electronics",
  },
  {
    name: "Men Cargo Pants",
    price: 2000,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/men cargo pants.jpg"),
    description: "Durable and stylish cargo pants for men.",
    units: Math.floor(Math.random() * 25) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Fashion",
  },
  {
    name: "Nokia Button Phone",
    price: 2500,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/nokia button.jpg"),
    description: "Reliable Nokia button phone with long battery life.",
    units: Math.floor(Math.random() * 30) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Electronics",
  },
  {
    name: "Vitro Sub Woofer",
    price: 6500,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/vitro sub woofer.jpg"),
    description: "High-quality Vitro subwoofer with powerful sound output.",
    units: Math.floor(Math.random() * 10) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Electronics",
  },
  {
    name: "Women Jeans",
    price: 2800,
    username: "Steve Don",
    avatar: require("@/assets/images/dongich.jpg"),
    image: require("@/assets/images/women jeans.jpg"),
    description: "Trendy and comfortable jeans for women.",
    units: Math.floor(Math.random() * 30) + 1,
    isSecondHand: Math.random() < 0.5,
    negotiable: Math.random() < 0.5,
    category: "Fashion",
  },
];
